### your site title here

title: Alison's portfolio
description: Data Analyst | Report Developer

baseurl: #name of GitHub repository
url: https://alisonsbpark.github.io #custom url to be used instead of GitHub repository
email: #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: 
linkedin: 
stackoverflow: 
github: 
researchgate: 
orcid: 
quora: 
instagram: 
facebook:

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - ccbhc_sra_report.md
      - ccbhc_sra_report copy.md
      - ccbhc_sra_report copy 2.md
      - ccbhc_sra_report copy 3.md
      - ccbhc_sra_report copy 4.md
      - ccbhc_sra_report copy 5.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
